sudo: required
services: docker
before_install:
  - docker build -t rumeeahmed/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true rumeeahmed/react-test npm test
after_success:
  #  Build the Images
  - docker build -t rumeeahmed/multi-client ./client
  - docker build -t rumeeahmed/multi-nginx ./nginx
  - docker build -t rumeeahmed/multi-server ./server
  - docker build -t rumeeahmed/multi-worker ./worker
  # Login to Docker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Push the images to Docker Hub
  - docker push rumeeahmed/multi-client
  - docker push rumeeahmed/multi-nginx
  - docker push rumeeahmed/multi-server
  - docker push rumeeahmed/multi-worker
language: generic
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Multi-Docker"
    env: "Multidocker-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-915091059854"
    bucket_path: "Multi-Docker"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY