version: '3'
services:
    api:
        image: 'rumeeahmed/multi-server'
        mem_limit: 128m
        volumes:
            - /app/node_modules
            - ./server:/app
    client:
        stdin_open: true
        image: rumeeahmed/multi-client
        mem_limit: 128m
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        image: 'rumeeahmed/multi-worker'
        mem_limit: 128m
        volumes:
            - /app/node_modules
            - ./worker:/app
    nginx:
        depends_on:
        - api
        - client
        restart: always
        image: 'rumeeahmed/multi-nginx'
        mem_limit: 128m
        ports:
            - '80:80'